.TH AR 5
.SH ИМЯ
ar \- формат архивного (библиотечного) файла
.SH ФОРМАТ
# include <ar.h>
.SH ОПИСАНИЕ
.PP
Команда ar(1)
используется для объединения нескольких файлов в один архивный файл.
Архивный файл используется, в основном, в качестве библиотеки для
редактора связей ld.
.PP
Файл, созданный командой ar
начинается со слова, содержащего "магический" признак ARMAG,
за которым следуют все составляющие
архив файлы. Каждый файл начинается с заголовка:
.ES L
# define ARMAG          0177545
# define ARHDRSZ        48

struct ar_hdr {
	char	ar_name [14];
	long	ar_date;
	int	ar_uid;
	int	ar_gid;
	int	ar_mode;
	long	ar_size;
};
.EE
.LP
Имя дополняется символом "пусто".
Время последнего изменения файла на момент записи в архив заносится в
ar_date.
.PP
Каждый файл начинается с четной границы; если необходимо,
между файлами вставляется дополнительный символ.
Однако размер отражает фактическую длину файла, без учета вставки.
.PP
Следует обратить внимание, что в архивном файле не предусмотрены
пустые участки.
.SH "ДОПОЛНИТЕЛЬНЫЕ ССЫЛКИ"
ar(1), ld(1), nm(1)
