.TH AS 1
.SH ИМЯ
as \- ассемблер
.SH ФОРМАТ
as [-u] [-x] [-X] [-o обфайл] [файл]
.SH ОПИСАНИЕ
.PP
Команда as ассемблирует файл с указанным именем или
стандартный файл ввода, если имя файла не задано.
Результат помещается в файл "a.out".
По умолчанию все неопределенные имена считаются внешними.
Можно задавать следующие флаги:
.IP -o
параметр, следующий за флагом "-o", задает имя выходного файла вместо "a.out"
.IP -u
не считать неопределенные имена внешними
.IP -x
не записывать в выходной файл информацию о локальных символах
.IP -X
не записывать в выходной файл информацию о локальных символах,
начинающихся с буквы 'L'.
.SH ФАЙЛЫ
.IP a.out 1.5i
объектный файл
.SH "ДОПОЛНИТЕЛЬНЫЕ ССЫЛКИ"
ld(1), nm(1), adb(1), a.out(5)
