.TH LORDER 1
.SH ИМЯ
lorder \- определить связи объектных файлов.
.SH ФОРМАТ
lorder файл ...
.SH ОПИСАНИЕ
Входная информация представляет собой один или несколько объектных
библиотечных или архивных (см. ar(1)) файлов. В результате работы
получается список пар имен объектных файлов.
Первый файл пары ссылается
на внешний идентификатор, определенный во втором. Выход
может быть обработан командой tsort(1) для нахождения
такого порядка размещения модулей в библиотеке,
который обеспечивает однопроходный поиск для ld(1).
.PP
Следующая строка предназначена для построения новой
библиотеки из существующих файлов ".o":
.IP
ar cr library `lorder *.o | tsort`
.SH "ДОПОЛНИТЕЛЬНЫЕ ССЫЛКИ"
tsort(1), ld(1), ar(1)
.SH ЗАМЕЧАНИЯ
Имена объектных файлов как внутри, так и вне
библиотек, должны иметь окончание ".o" - в противном
случае результат будет бессмысленным.

