.TH STRIP 1
.SH ИМЯ
strip \- удалить таблицу символов.
.SH ФОРМАТ
strip имя ...
.SH ОПИСАНИЕ
Команда strip удаляет таблицу символов и биты
перемещения, которые обычно содержатся в выводных файлах
ассемблера и редактора связей.
Используется для сокращения объема памяти для хранения выполняемого
кода отлаженной программы.
.PP
Действие команды strip аналогично использованию ключа "-s" в команде ld.
.PP
.SH ФАЙЛЫ
.IP /tmp/s?????? 1.5i
временный файл.
.SH "ДОПОЛНИТЕЛЬНЫЕ ССЫЛКИ"
ld(1)
